client:
  hosts:
    - ${ES_HOST:elasticsearch}
  port: ${ES_PORT:9200}
  url_prefix:
  use_ssl: False
  certificate:
  client_cert:
  client_key:
  ssl_no_validate: True
  http_auth:
  timeout: ${CURATOR_TIMEOUT:120}
  master_only: ${CURATOR_MASTER_ONLY:False}
logging:
  loglevel: ${CURATOR_LOGLEVEL:INFO}
  logfile:
  logformat: ${CURATOR_LOGFORMAT:default}
  #blacklist: ['elasticsearch', 'urllib3']
